version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
      - run: yarn test
