name: Helper

on:
  pull_request_target:
    types:
      - closed

jobs:
  instructions:
    name: instructions
    runs-on: ubuntu-latest
    if: 
    steps:
      - uses: actions/checkout@v2
      - name: Comment
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { hasLabel } = require(`${process.env.GITHUB_WORKSPACE}/scripts/action-utils.js`);
            const { instructions } = require(`${process.env.GITHUB_WORKSPACE}/scripts/reply.js`);
            if (hasLabel(context, 'domain'))
              await instructions(context, github);
