# https://github.com/actions/labeler

name: Checks
on: [pull_request_target]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Installing dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Running tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Labelling pull request
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
