name: Checks
on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Installing dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --ignore-engines
      - name: Running tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
