name: validation
on: [push]

jobs:
  test:
    name: Validation
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 14.x 
      uses: actions/setup-node@v1
      with:
        version: 14.x

    - name: Install dependencies
      run: yarn

    - name: Test and verify domains
      run: CI=true yarn test
