name: GitHub ID

on:
    pull_request:
        branches: [main]

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get changed files
              id: files
              uses: jitterbit/get-changed-files@v1
              with:
                  format: "space-delimited"

            - name: Run script
              uses: is-a-dev/github-id-script@latest
              with:
                  files: ${{ steps.files.outputs.all }}

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_user_name: "GitHub Actions"
                  commit_user_email: "actions@github.com"
                  commit_message: "chore: add github user id"
