name: Publish records

on:
  workflow_dispatch:
    name: 'Publish records'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CI: 1
      ENV: production
      DOMAIN_USER: ${{ secrets.DOMAIN_USER }}
      DOMAIN_API_KEY: ${{ secrets.DOMAIN_API_KEY }}
      DOMAIN_API_HOST: ${{ secrets.DOMAIN_API_HOST }}
      DOMAIN_API_PORT: ${{ secrets.DOMAIN_API_PORT }}
      DOMAIN_DOMAIN: ${{ secrets.DOMAIN_DOMAIN }}
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Publishing records
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: publish-records
